name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add any additional dependencies needed for testing

    - name: Run flask api Tests using pytest
      run: |
        pytest .OCDSP7/tests/unit_test.py

    - name: Login to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

    - name: Deploy to Heroku
      run: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/credit-score-app.git HEAD:refs/heads/main
        heroku run python manage.py migrate

    - name: Get Heroku URL
      run: echo "https://credit-score-appherokuapp.com" >> url.txt

    - name: Upload URL artifact
      uses: actions/upload-artifact@v2
      with:
        name: heroku-url
        path: url.txt    